import os

TELEGRAM_TOKEN = os.environ["TELEGRAM_TOKEN"]
OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]

MORNING_REPORT_HOUR = 6   # 09:00 MSK = 06:00 UTC
EVENING_REPORT_HOUR = 17  # 20:00 MSK = 17:00 UTC
